### ISSUE TITLE
Unable to logout

### ISSUE THREAD

**Issue by foliodev** [cotterapp/cotter-js#17]
<img width="611" alt="Screen Shot 2020-09-20 at 4 17 35 pm" src="https://user-images.githubusercontent.com/865672/93704998-e07be380-fb5c-11ea-99fd-a3c539c1355e.png">
Please use localStorage.removeItem("COTTER_KEYS"); from https://js.cotter.app when cotter.logOut() is called.
This appears to be in an iframe and therefore preferably be removed as it was stored from https://js.cotter.app.

This will enable re-authentication of users when logout is called.
Otherwise, even by deleting the cookie refreshToken, these keys seem to allow obtaining re-authentication again without need for checking email, thereby defeating the purpose in calling the DELETE refresh token cookie and may therefore be a security issue.

**Comment by putrikarunia** [comment]
The `cotter.logOut()` function is used to "log out from your website, but not from Cotter". **The behavior where users are not required to re-verify their email after calling this log out function is expected**. You can read more about [how Cotter's Sign In with Email or Phone works](https://docs.cotter.app/features/verify-email-phone).

It's because we are an identity provider and it works like Sign in with Google. If you log in to Medium or Intercom with Google, then try to **Log Out from Medium or Intercom**, when you **Sign in with Google** again you won't be asked to enter your password because you're still logged-in with Google.

That works the same with us. Calling the **logOut** function from the SDK will make the users log out **from your website, but not from Cotter** (the equivalent of logging-out from Medium/Intercom, but not from Google). If your users log out from your site they are still "logged-in" with Cotter and won't need to re-verify their email again when using Cotter's login form. This session lasts for 30 days, after which they will have to re-verify their email again. 

We are adding the functionality for users to **log out from Cotter** (the equivalent of logging out from Google). With this functionality, users can go to Cotter's Website, see their profile, and log out from Cotter. This will force them to re-verify their email the next time they use a Cotter Login Form.
