### ISSUE TITLE
Updating email

### ISSUE THREAD

**Issue by foliodev** [cotterapp/cotter-js#18]
Hi 
I spoke to Putri the other day in regards to keeping same cotterUID in the "sub" parameter (CotterUserID) of the access token but changing email address/identity. That way my own db can rely on the permanent CotterUserID to identify the user while the change in email will in turn change the email in my DB.

She suggested using this:
`ApiKeyID: "APIKEY",
CotterUserID: "USERID" // 👈 pass in Cotter User ID
});
cotter
.signInWithLink()
.showEmailForm()
.then(payload => {
this.success = true;
this.payload = payload;
this.accessToken = this.payload.oauth_token.access_token;`

Unfortunately this did nothing. It only created a new user. 
Please advise on how to implement changing email address/identity linked to a specific CotterUserID.
If this is possible, please also advise on how Cotter handles duplicates for example if an email(lets call this email1) is already bound to a specific CotterUserID but another CotterUserID is intending to change emails to email1.

**Comment by putrikarunia** [comment]
Hi @scorpnode, as an update, **changing the email for now only works with `signInWithOTP`**, so you can do:
```javascript
      var cotter = new Cotter({
        ApiKeyID: "API_KEY_ID",
        CotterUserID: "COTTER_USER_ID" // Cotter user id of the user that want to change email
      });

      cotter
        .signInWithOTP()
        .showEmailForm()
        .then((payload) => {
          // Read what Cotter Returns
        })
        .catch((err) => {
          // handle any errors here
          console.log(err);
        });
``` 

The user has to use a new email address, otherwise, you'll catch an error "User with this identifier already exists".

**You can find the user's Cotter User ID from:**
- The returned User object after the user logs in from `user.id`
- The `sub` field of both the access_token and the id_token.
